### ISSUE TITLE
nominatim

### ISSUE THREAD

**Issue by couleurmate** [C4ptainCrunch/DeweyMaps#14]
http://wiki.openstreetmap.org/wiki/Nominatim

**Comment by C4ptainCrunch** [comment]
C'est quoi l'idée ? De permettre aux gens de déplacer la carte à une adresse précise ? De deviner l'adresse des points sur la carte ? De permettre aux gens d'ajouter un point à une adresse et pas à des coordonnées ?

De nouveau, ce sont 3 problèmes assez séparés, à implémenter à des endroits différents dans le code, il vaut mieux avoir 3 issues différentes pour tracker leur faisablilité et éventuellement leur avancement.
